server.port=8086
spring.datasource.url=jdbc:mysql://localhost:3306/booknest_reviews?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=@rawat2525KHUSHI
spring.jpa.hibernate.ddl-auto=update
spring.application.name=review-service

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
