sonar.projectKey=khushikumari90_BookNest-Frontend
sonar.organization=khushikumari90
sonar.projectName=BookNest Angular Frontend

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**,**/.angular/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/booknest-angular/lcov.info
